### ISSUE TITLE
SUMMARY: Meets Expectations

### ISSUE THREAD

**Issue by jzhu01** [K-T-K/prj-rev-bwfs-dasmoto#5]
Fantastic job on this project! I really liked your setting the font family once, and how clean and easy to read your code was. In terms of improvement, I recommend adding quotes around your IDs, and removing the `font-weight:bold` on your headings. 
 
If you’re in the mood for a challenge...I would look into adding more items under each section and finding a nice way to lay them out. Here's a link to get you started - https://www.w3schools.com/css/css_rwd_grid.asp. Keep up the hard work! ^_^

**Comment by K-T-K** [comment]
Thank you. This is the first time I have used GitHub... should I make these recommended changes. Should I make them here in GH (assuming GH allows me this capability) or just in my file on my desktop? 

Thanks for the extra challenge... I will def work on it. 

Last but not least should I be closing these comments? I am not sure what the common or best practice is.

Thanks! 

-K

**Comment by jzhu01** [comment]
Good questions! I just saw this, sorry for the delay. It's up to you whether or not to make the changes, and also up to you whether or not to close them! I know some people like to close them once they've made the changes, but again, it is up to you! 😊
